const stateCityMapOfCanadaAndUS = {
    //canada state city data api
    AB: ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "St. Albert", "Medicine Hat", "Grande Prairie", "Airdrie", "Spruce Grove", "Leduc", "Fort Saskatchewan", "Lloydminster", "Camrose", "Chestermere", "Okotoks"],
    BC: ["Vancouver", "Surrey", "Burnaby", "Richmond", "Abbotsford", "Coquitlam", "Kelowna", "Langley", "Saanich", "Delta", "Nanaimo", "Kamloops", "Chilliwack", "Victoria", "Maple Ridge"],
    MB: ["Winnipeg", "Brandon", "Steinbach", "Thompson", "Portage la Prairie", "Selkirk", "Winkler", "Morden", "Dauphin", "Flin Flon", "The Pas", "Stonewall", "Niverville", "Swan River", "Neepawa"],
    NB: ["Moncton", "Saint John", "Fredericton", "Dieppe", "Miramichi", "Bathurst", "Edmundston", "Campbellton", "Oromocto", "Sackville", "Quispamsis", "Riverview", "Grand Bay-Westfield", "Rothesay", "Woodstock"],
    NL: ["St. John's", "Mount Pearl", "Corner Brook", "Conception Bay South", "Paradise", "Gander", "Grand Falls-Windsor", "Happy Valley-Goose Bay", "Labrador City", "Stephenville", "Clarenville", "Marystown", "Bay Roberts", "Deer Lake", "Carbonear"],
    NS: ["Halifax", "Sydney", "Truro", "New Glasgow", "Glace Bay", "Kentville", "Bridgewater", "Yarmouth", "Amherst", "Antigonish", "Wolfville", "Dartmouth", "Bedford", "Lunenburg", "Pictou"],
    NT: ["Yellowknife", "Hay River", "Inuvik", "Fort Smith", "Behchokǫ̀", "Fort Simpson", "Norman Wells", "Tuktoyaktuk", "Fort McPherson", "Aklavik", "Fort Providence", "Délı̨nę", "Fort Resolution", "Gamètì", "Wekweètì"],
    NU: ["Iqaluit", "Rankin Inlet", "Arviat", "Baker Lake", "Cambridge Bay", "Pond Inlet", "Igloolik", "Pangnirtung", "Kugluktuk", "Coral Harbour", "Kinngait", "Gjoa Haven", "Naujaat", "Qikiqtarjuaq", "Sanikiluaq"],
    ON: ["Toronto", 'AJAX', 'BANCROFT', 'BURLINGTON', 'CHATHAM', 'HAWKESBURY', 'KINGSTON','MARKHAM', 'MISSISSAUGA', 'NEPEAN', 'NEWMARKET', 'OAKVILLE', 'OTTAWA', 'ONLINE ONLY','PEMBROKE', 'PICKERING', 'RICHMOND HILL', 'SCARBOROUGH', 'STRATFORD', 'THORNHILL', 'THOROLD','TILBURY', 'TORONTO', 'UNIONVILLE', 'VAUGHAN', 'WINDSOR', 'WOODBRIDGE', "Tilbury", "Thornhill", "Ottawa", "Mississauga", "Brampton", "Hamilton", "London", "Markham", "Vaughan", "Kitchener", "Windsor", "Richmond Hill", "Oakville", "Burlington", "Greater Sudbury", "Oshawa"],
    PE: ["Charlottetown", "Summerside", "Stratford", "Cornwall", "Montague", "Kensington", "Souris", "Alberton", "Georgetown", "Tignish", "Borden-Carleton", "Hunter River", "Morell", "Murray River", "North Rustico"],
    QC: ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil", "Sherbrooke", "Saguenay", "Levis", "Trois-Rivières", "Terrebonne", "Saint-Jean-sur-Richelieu", "Repentigny", "Drummondville", "Saint-Jérôme", "Granby"],
    SK: ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw", "Yorkton", "Swift Current", "North Battleford", "Estevan", "Weyburn", "Martensville", "Humboldt", "Melfort", "Meadow Lake", "Lloydminster", "Kindersley"],
    YT: ["Whitehorse", "Dawson City", "Watson Lake", "Haines Junction", "Carmacks", "Faro", "Teslin", "Mayo", "Ross River", "Pelly Crossing", "Burwash Landing", "Destruction Bay", "Beaver Creek", "Old Crow", "Tagish"],
    //usa state city data api
    AL: ["Huntsville", "W Huntsville", "Birmingham", "Montgomery", "Mobile", "Tuscaloosa", "Hoover", "Dothan", "Auburn", "Decatur", "Madison", "Florence", "Gadsden", "Vestavia Hills", "Phenix City", "Prattville"],
    AK: ["Anchorage", "Hwy Anchorage", "Fairbanks", "Juneau", "Wasilla", "Sitka", "Ketchikan", "Kenai", "Kodiak", "Bethel", "Palmer", "Homer", "Soldotna", "Unalaska", "Valdez", "Nome"],
    AZ: ["Phoenix", "Tucson", "Mesa", "Chandler", "Gilbert", "Glendale", "Scottsdale", "Peoria", "Tempe", "Surprise", "San Tan Valley", "Goodyear", "Buckeye", "Avondale", "Lake Havasu City"],
    AR: ["Little Rock", "Fayetteville", "Fort Smith", "Springdale", "Jonesboro", "Rogers", "Conway", "North Little Rock", "Bentonville", "Pine Bluff", "Hot Springs", "Benton", "Sherwood", "Texarkana", "Russellville"],
    CA: ["Cathedral City", "Rancho Mirage", "Humboldt County", "Vacaville", "Los Angeles", "Cathedral City", "San Diego", "San Jose", "San Francisco", "Fresno", "Sacramento", "Long Beach", "Oakland", "Bakersfield", "Anaheim", "Santa Ana", "Riverside", "Stockton", "Irvine", "Chula Vista"],
    CO: ['Colorado Springs', 'Grand Junction', "Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Thornton", "Arvada", "Westminster", "Pueblo", "Centennial", "Boulder", "Greeley", "Longmont", "Loveland", "Broomfield"],
    CT: ["Bridgeport", "Stamford", "New Haven", "Hartford", "Waterbury", "Norwalk", "Danbury", "New Britain", "West Hartford", "Greenwich", "Fairfield", "Hamden", "Meriden", "Bristol", "Manchester"],
    DE: ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna", "Milford", "Seaford", "Georgetown", "Elsmere", "New Castle", "Millsboro", "Laurel", "Harrington", "Camden", "Claymont"],
    FL: ['Palmetto Bay', 'LAKE PARK', "Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Hialeah", "Port St. Lucie", "Cape Coral", "Tallahassee", "Fort Lauderdale", "Pembroke Pines", "Hollywood", "Miramar", "Gainesville", "Coral Springs"],
    GA: ["Atlanta", "Columbus", "Augusta", "Macon", "Savannah", "Athens", "Sandy Springs", "South Fulton", "Roswell", "Johns Creek", "Warner Robins", "Albany", "Alpharetta", "Marietta", "Valdosta"],
    HI: ["Honolulu", "East Honolulu", "Pearl City", "Hilo", "Waipahu", "Kailua", "Kaneohe", "Mililani Town", "Ewa Gentry", "Kahului", "Mililani Mauka", "Kihei", "Makakilo", "Wahiawa", "Schofield Barracks"],
    ID: ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello", "Caldwell", "Twin Falls", "Lewiston", "Post Falls", "Rexburg", "Eagle", "Moscow", "Ammon", "Chubbuck", "Mountain Home"],
    IL: ["Chicago", "Pkwy Bloomington", 'Ave Ardmore', 'Quad Cities', "Aurora", "Naperville", "Joliet", "Rockford", "Springfield", "Elgin", "Peoria", "Champaign", "Waukegan", "Cicero", "Bloomington", "Arlington Heights", "Evanston", "Decatur"],
    IN: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel", "Fishers", "Bloomington", "Hammond", "Gary", "Lafayette", "Muncie", "Noblesville", "Terre Haute", "Greenwood", "Kokomo"],
    IA: ["Des Moines", 'Quad Cities', "Cedar Rapids", "Davenport", "Sioux City", "Iowa City", "Ankeny", "West Des Moines", "Ames", "Council Bluffs", "Dubuque", "Urbandale", "Cedar Falls", "Marion", "Bettendorf", "Mason City"],
    KS: ["Wichita", 'Road WICHITA', "Overland Park", "Kansas City", "Olathe", "Topeka", "Lawrence", "Shawnee", "Manhattan", "Lenexa", "Salina", "Hutchinson", "Leavenworth", "Leawood", "Dodge City", "Garden City"],
    KY: ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington", "Richmond", "Georgetown", "Florence", "Hopkinsville", "Nicholasville", "Elizabethtown", "Henderson", "Frankfort", "Jeffersontown", "Paducah"],
    LA: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles", "Kenner", "Bossier City", "Monroe", "Alexandria", "Houma", "New Iberia", "Central", "Slidell", "Ruston", "Hammond"],
    ME: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn", "Biddeford", "Sanford", "Saco", "Westbrook", "Augusta", "Waterville", "Presque Isle", "Brewer", "Bath", "Ellsworth"],
    MD: ["Baltimore", "Frederick", 'Pocomoke City', "Rockville", "Gaithersburg", "Bowie", "Hagerstown", "Annapolis", "College Park", "Salisbury", "Laurel", "Greenbelt", "Cumberland", "Westminster", "Hyattsville", "Takoma Park"],
    MA: ["Rd Hyannis", 'Norwood', "Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton", "Quincy", "Lynn", "New Bedford", "Fall River", "Newton", "Somerville", "Lawrence", "Framingham", "Waltham"],
    MI: ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor", "Lansing", "Flint", "Dearborn", "Livonia", "Troy", "Westland", "Farmington Hills", "Kalamazoo", "Wyoming", "Southfield"],
    MN: ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington", "Brooklyn Park", "Plymouth", "Maple Grove", "Woodbury", "St. Cloud", "Eagan", "Eden Prairie", "Coon Rapids", "Burnsville", "Blaine"],
    MS: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi", "Meridian", "Tupelo", "Olive Branch", "Greenville", "Horn Lake", "Pearl", "Madison", "Starkville", "Clinton", "Ridgeland"],
    MO: ["Kansas City", 'Joplin', "St. Louis", "Springfield", "Columbia", "Independence", "Lee's Summit", "O'Fallon", "St. Joseph", "St. Charles", "Blue Springs", "St. Peters", "Florissant", "Joplin", "Chesterfield", "Jefferson City"],
    MT: ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte", "Helena", "Kalispell", "Havre", "Anaconda", "Miles City", "Belgrade", "Livingston", "Laurel", "Whitefish", "Lewistown"],
    NE: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney", "Fremont", "Hastings", "Norfolk", "North Platte", "Columbus", "Papillion", "La Vista", "Scottsbluff", "South Sioux City", "Beatrice"],
    NV: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks", "Carson City", "Fernley", "Elko", "Mesquite", "Boulder City", "Fallon", "Winnemucca", "West Wendover", "Ely", "Yerington"],
    NH: ["Manchester", "Nashua", "Concord", "Derry", "Dover", "Rochester", "Salem", "Merrimack", "Hudson", "Londonderry", "Keene", "Portsmouth", "Bedford", "Goffstown", "Laconia"],
    NJ: ["Newark", 'NJ Edison', "Jersey City", "Paterson", "Elizabeth", "Edison", "Woodbridge", "Lakewood", "Toms River", "Hamilton", "Trenton", "Clifton", "Camden", "Brick", "Cherry Hill", "Passaic"],
    NM: ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell", "Farmington", "Clovis", "Hobbs", "Alamogordo", "Carlsbad", "Gallup", "Los Lunas", "Sunland Park", "Deming", "Chaparral"],
    NY: ["New York", 'NY-23 Oneonta', "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany", "New Rochelle", "Mount Vernon", "Schenectady", "Utica", "White Plains", "Hempstead", "Troy", "Niagara Falls", "Binghamton"],
    NC: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville", "Cary", "Wilmington", "High Point", "Greenville", "Asheville", "Concord", "Gastonia", "Jacksonville", "Chapel Hill"],
    ND: ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo", "Williston", "Dickinson", "Mandan", "Jamestown", "Wahpeton", "Devils Lake", "Valley City", "Grafton", "Beulah", "Horace"],
    OH: ["Columbus", 'Ave Youngstown', 'Rd. Columbus', 'Ave Waverly', 'Rd Boardman', "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton", "Parma", "Canton", "Youngstown", "Lorain", "Hamilton", "Springfield", "Kettering", "Elyria", "Lakewood"],
    OK: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond", "Lawton", "Moore", "Midwest City", "Enid", "Stillwater", "Muskogee", "Bartlesville", "Owasso", "Shawnee", "Yukon"],
    OR: ["Ave Medford", 'Klamath Falls', "Portland", "Salem", "Eugene", "Gresham", "Hillsboro", "Beaverton", "Bend", "Medford", "Springfield", "Corvallis", "Tigard", "Albany", "Lake Oswego", "Keizer", "Grants Pass"],
    PA: ['Blvd Altoona','Drive Wilkes-Barre', 'Jersey Shore',"Ave ardmore", "Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Scranton", "Bethlehem", "Lancaster", "Harrisburg", "York", "Altoona", "Wilkes-Barre", "State College", "Chester", "Easton"],
    RI: ["Providence", "Cranston", "Warwick", "Pawtucket", "East Providence", "Woonsocket", "Coventry", "Cumberland", "North Providence", "South Kingstown", "West Warwick", "Johnston", "North Kingstown", "Newport", "Bristol"],
    SC: ['Blvd Altoona', 'Ave Ardmore', 'Drive Wilkes-Barre', 'Jersey Shore', "Charleston", "Columbia", "North Charleston", "Mount Pleasant", "Rock Hill", "Greenville", "Summerville", "Goose Creek", "Sumter", "Florence", "Spartanburg", "Hilton Head Island", "Greer", "Aiken", "Myrtle Beach"],
    SD: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown", "Mitchell", "Yankton", "Pierre", "Huron", "Vermillion", "Spearfish", "Brandon", "Box Elder", "Sturgis", "Madison"],
    TN: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro", "Franklin", "Jackson", "Johnson City", "Bartlett", "Hendersonville", "Kingsport", "Collierville", "Smyrna", "Germantown"],
    TX: ['Midland',"Houston", "San Antonio", "San Angelo", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington", "Corpus Christi", "Plano", "Lubbock", "Laredo", "Irving", "Garland", "Frisco", "McKinney"],
    UT: ["Salt Lake City", "West Valley City", "West Jordan", "Provo", "St. George", "Orem", "Sandy", "Ogden", "Layton", "South Jordan", "Lehi", "Millcreek", "Taylorsville", "Logan", "Murray"],
    VT: ["Burlington", "South Burlington", "Rutland", "Essex Junction", "Barre", "Montpelier", "Winooski", "St. Albans", "Newport", "Vergennes", "St. Johnsbury", "Brattleboro", "Bennington", "Middlebury", "Springfield"],
    VA: ["Virginia Beach", "Chesapeake", "Norfolk", "Richmond", "Newport News", "Alexandria", "Hampton", "Roanoke", "Portsmouth", "Suffolk", "Lynchburg", "Harrisonburg", "Leesburg", "Charlottesville", "Danville"],
    WA: ['St Bellevue',"Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kent", "Everett", "Renton", "Spokane Valley", "Federal Way", "Yakima", "Bellingham", "Kirkland", "Auburn", "Kennewick"],
    WV: ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling", "Weirton", "Fairmont", "Martinsburg", "Beckley", "Clarksburg", "South Charleston", "St. Albans", "Vienna", "Bluefield", "Bridgeport"],
    WI: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton", "Waukesha", "Eau Claire", "Oshkosh", "Janesville", "West Allis", "La Crosse", "Sheboygan", "Wauwatosa", "Fond du Lac"],
    WY: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs", "Sheridan", "Green River", "Evanston", "Riverton", "Jackson", "Cody", "Rawlins", "Lander", "Torrington", "Douglas"],
    'N/A': ['N/A', 'ONLINE ONLY'],
};

export default stateCityMapOfCanadaAndUS;
